name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::307946668157:role/cv-html-repo-accessRole
          aws-region: us-east-1

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://mohamedmujtaba --delete

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36 # Or latest
        with:
          format: json
          base_sha: ${{ github.event.before || 'HEAD^' }}
          sha: ${{ github.sha }}

      - name: Invalidate CloudFront Cache
        if: steps.changed-files.outputs.all_changed_files != '[]'
        run: |
          echo "Changed Files (JSON): ${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Changed Files (Count): ${{ steps.changed-files.outputs.all_changed_files_count }}"

          # Improved jq command to handle spaces and special characters safely
          CHANGED_PATHS=$(echo '${{ steps.changed-files.outputs.all_changed_files }}' | jq -r '.[] | @json')

          # Construct the invalidation batch JSON directly
          INVALIDATION_BATCH='{ "Paths": { "Quantity": ${{ steps.changed-files.outputs.all_changed_files_count }}, "Items": [${{ env.CHANGED_PATHS }}] } }'

          echo "Invalidation Batch: $INVALIDATION_BATCH"  # Debugging

          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --invalidation-batch "$INVALIDATION_BATCH"  # Use --invalidation-batch

        env:
          CHANGED_PATHS: ''

      - name: Debug Commit SHAs
        run: |
          echo "Previous SHA (github.event.before): ${{ github.event.before }}"
          echo "Current SHA (github.sha): ${{ github.sha }}"
